In [2]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

In [1]:
import investprox

In [2]:
import voteprox

In [5]:
investprox.proximity(np.array([[0,0,0,1,0,0,0,0,0,0],[0,0,1,0,1,0,0,0,1,0],[0,0,1,0,0,0,0,0,0,0],[0,1,0,1,0,0,0,0,0,0],[0,1,0,0,0,0,0,0,0,0],[0,0,0,0,0,1,0,0,0,0],[0,0,0,0,1,0,1,0,0,1],[0,0,0,0,0,1,0,0,0,0],[0,0,0,0,0,0,0,0,1,0],[1,1,0,0,0,0,0,0,0,0],[1,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,1],[0,0,1,0,0,0,0,0,0,0],[0,0,0,1,1,0,1,1,1,1],[0,0,0,0,1,0,0,0,0,0],[0,1,1,0,1,0,0,0,1,0],[1,1,0,0,0,1,1,0,0,0],[0,0,0,0,0,0,0,0,0,1],[0,0,1,0,0,0,0,0,0,1],[1,0,0,1,1,0,1,0,0,0],[0,0,0,0,0,0,0,1,0,0],[1,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,1,1,0,1,0],[1,0,0,0,0,0,0,0,0,0],[0,0,0,0,1,1,0,1,0,0],[0,0,1,0,0,0,0,0,0,0],[1,0,0,0,0,0,0,0,0,0],[0,0,0,1,0,0,0,0,0,1],[0,0,0,0,0,0,0,1,0,0],[1,1,1,0,0,0,0,1,0,0],[0,1,0,1,0,0,0,0,0,0],[0,0,0,0,0,1,0,0,0,0],[0,0,0,0,0,0,1,0,0,0]]))

A:
[[0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 0 1 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 1]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 1 1 1 1]
 [0 0 0 0 1 0 0 0 0 0]
 [0 1 1 0 1 0 0 0 1 0]
 [1 1 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0 0 1]
 [1 0 0 1 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 1 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 1 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1 0 0]
 [1 1 1 0 0 0 0 1 0 0]
 [0 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]]

Transpose of A:
[[0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 1 0 0 1 0 0 0]
 [0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0]
 [1 0 0 1 0 0

In [6]:
voteprox.proximity(np.array([[1,-1,1,1,1,1,1,1,1,1,-1,-1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,-1,1,1,1,1,1,1,1,-1,-1,-1,-1,-1],[0,1,1,1,1,1,1,1,1,-1,-1,-1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,-1,1,1,1,1],[1,1,1,1,1,1,1,1,1,-1,-1,-1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,-1,1,1,1,1,1,1,1,1,-1,-1,1,1],[1,-1,1,1,0,1,1,1,1,1,-1,-1,1,1],[1,1,1,0,1,1,1,1,1,1,1,1,1,1],[1,-1,1,1,1,1,1,1,1,1,-1,-1,1,1],[-1,-1,1,1,-1,-1,1,1,-1,0,-1,-1,1,-1],[1,-1,0,1,1,1,1,1,1,1,-1,-1,1,-1],[1,-1,1,1,1,1,1,1,1,-1,-1,-1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,-1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1,-1,-1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,-1,1,1,1,1],[1,-1,1,1,1,1,1,1,1,1,-1,-1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1,-1,-1,1,1],[1,1,1,1,1,1,1,1,1,1,-1,-1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1,-1,-1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,-1,1,1,1,1,1,1,1,1,-1,-1,1,1],[1,-1,1,1,1,1,1,1,-1,-1,-1,-1,1,1],[1,1,1,1,1,1,1,1,1,1,-1,-1,1,1],[1,-1,1,1,1,1,1,1,1,1,-1,-1,1,1],[1,-1,1,1,1,1,1,1,1,1,-1,-1,1,1]]))

A:
[[ 1 -1  1  1  1  1  1  1  1  1 -1 -1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1 -1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1]
 [ 0  1  1  1  1  1  1  1  1 -1 -1 -1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1 -1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1 -1 -1 -1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1 -1  1  1  1  1  1  1  1  1 -1 -1  1  1]
 [ 1 -1  1  1  0  1  1  1  1  1 -1 -1  1  1]
 [ 1  1  1  0  1  1  1  1  1  1  1  1  1  1]
 [ 1 -1  1  1  1  1  1  1  1  1 -1 -1  1  1]
 [-1 -1  1  1 -1 -1  1  1 -1  0 -1 -1  1 -1]
 [ 1 -1  0  1  1  1  1  1  1  1 -1 -1  1 -1]
 [ 1 -1  1  1  1  1  1  1  1 -1 -1 -1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1 -1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1 -1 -1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1 -1  1  1  1  1]
 [ 1 -1  1  1  1  1  1  1  1  1 -1 -1  1  1]
 [ 1  1

In [7]:
n = votingproximity.shape[0]
print('n')
politicians = range(n)

NameError: name 'votingproximity' is not defined

In [8]:
print(votingproximity)

NameError: name 'votingproximity' is not defined

In [18]:
A = np.array([[1,-1,1,1,1,1,1,1,1,1,-1,-1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1],[0,1,1,1,1,1,1,1,1,-1,-1,-1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,-1,1,1,1,1],[1,1,1,1,1,1,1,1,1,-1,-1,-1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,-1,1,1,1,1,1,1,1,1,-1,-1,1,1],[1,-1,1,1,0,1,1,1,1,1,-1,-1,1,1],[1,1,1,0,1,1,1,1,1,1,1,1,1,1],[1,-1,1,1,1,1,1,1,1,1,-1,-1,1,1],[-1,-1,1,1,-1,-1,1,1,-1,0,-1,-1,1,-1],[1,-1,0,1,1,1,1,1,1,1,-1,-1,1,-1],[1,-1,1,1,1,1,1,1,1,-1,-1,-1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,-1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1,-1,-1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,-1,1,1,1,1],[1,-1,1,1,1,1,1,1,1,1,-1,-1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1,-1,-1,1,1],[1,1,1,1,1,1,1,1,1,1,-1,-1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1,-1,-1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,-1,1,1,1,1,1,1,1,1,-1,-1,1,1],[1,-1,1,1,1,1,1,1,-1,-1,-1,-1,1,1],[1,1,1,1,1,1,1,1,1,1,-1,-1,1,1],[1,-1,1,1,1,1,1,1,1,1,-1,-1,1,1],[1,-1,1,1,1,1,1,1,1,1,-1,-1,1,1]])

In [10]:
    print('A:')
    print(A)
    print()

A:
[[ 1 -1  1  1  1  1  1  1  1  1 -1 -1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1 -1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1]
 [ 0  1  1  1  1  1  1  1  1 -1 -1 -1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1 -1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1 -1 -1 -1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1 -1  1  1  1  1  1  1  1  1 -1 -1  1  1]
 [ 1 -1  1  1  0  1  1  1  1  1 -1 -1  1  1]
 [ 1  1  1  0  1  1  1  1  1  1  1  1  1  1]
 [ 1 -1  1  1  1  1  1  1  1  1 -1 -1  1  1]
 [-1 -1  1  1 -1 -1  1  1 -1  0 -1 -1  1 -1]
 [ 1 -1  0  1  1  1  1  1  1  1 -1 -1  1 -1]
 [ 1 -1  1  1  1  1  1  1  1 -1 -1 -1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1 -1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1 -1 -1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1 -1  1  1  1  1]
 [ 1 -1  1  1  1  1  1  1  1  1 -1 -1  1  1]
 [ 1  1

In [19]:
    B=A.T
    print('Transpose of A:')
    print(B)
    print()

    Q=A@B
    print('One-mode projection:')
    print(Q)
    print()

    votingproximity = (Q+14)/28
    print('Normalized One-mode projection:')
    print(votingproximity)

Transpose of A:
[[ 1  1  0  1  1  1  1  1  1  1  1  1 -1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1]
 [-1  1  1  1  1  1  1  1 -1 -1  1 -1 -1 -1 -1  1  1  1  1  1 -1  1  1  1
   1  1  1 -1 -1  1 -1 -1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  0  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  0  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  0  1  1 -1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1 -1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1 -1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1 -1  1  1  1]
 [ 1  1 -1  1 -1 -1  1  1  1  1  1  1  0  1 -1  1 -1  1  1 -1  1  1  1  1
 

In [14]:
print(votingproximity)

[[1.         0.78571429 0.78571429 ... 0.92857143 1.         1.        ]
 [0.78571429 1.         0.57142857 ... 0.85714286 0.78571429 0.78571429]
 [0.78571429 0.57142857 1.         ... 0.71428571 0.78571429 0.78571429]
 ...
 [0.92857143 0.85714286 0.71428571 ... 1.         0.92857143 0.92857143]
 [1.         0.78571429 0.78571429 ... 0.92857143 1.         1.        ]
 [1.         0.78571429 0.78571429 ... 0.92857143 1.         1.        ]]


In [16]:
A = np.array([[0,0,0,1,0,0,0,0,0,0],[0,0,1,0,1,0,0,0,1,0],[0,1,0,1,0,0,0,0,0,0],[0,1,0,0,0,0,0,0,0,0],[0,0,0,0,0,1,0,0,0,0],[0,0,0,0,1,0,1,0,0,1],[0,0,0,0,0,1,0,0,0,0],[0,0,0,0,0,0,0,0,1,0],[1,1,0,0,0,0,0,0,0,0],[1,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,1],[0,0,1,0,0,0,0,0,0,0],[0,0,0,1,1,0,1,1,1,1],[0,0,0,0,1,0,0,0,0,0],[0,1,1,0,1,0,0,0,1,0],[1,1,0,0,0,1,1,0,0,0],[0,0,0,0,0,0,0,0,0,1],[0,0,1,0,0,0,0,0,0,1],[1,0,0,1,1,0,1,0,0,0],[0,0,0,0,0,0,0,1,0,0],[1,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,1,1,0,1,0],[1,0,0,0,0,0,0,0,0,0],[0,0,0,0,1,1,0,1,0,0],[0,0,1,0,0,0,0,0,0,0],[1,0,0,0,0,0,0,0,0,0],[0,0,0,1,0,0,0,0,0,1],[0,0,0,0,0,0,0,1,0,0],[1,1,1,0,0,0,0,1,0,0],[0,1,0,1,0,0,0,0,0,0],[0,0,0,0,0,1,0,0,0,0],[0,0,0,0,0,0,1,0,0,0]])

In [17]:
    B=A.T
    print('Transpose of A:')
    print(B)
    print()

    Q=A@B
    print('One-mode projection:')
    print(Q)
    print()
    
    investingproximity = Q * 0.1
    print('Normalized One-mode projection:')
    print(investingproximity)

Transpose of A:
[[0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 1 0 0 1 0 0 0]
 [0 0 1 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0]
 [0 1 0 0 0 1 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 1 0 0 0]
 [0 1 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0]]

One-mode projection:
[[1 0 1 ... 1 0 0]
 [0 3 0 ... 0 0 0]
 [1 0 2 ... 2 0 0]
 ...
 [1 0 2 ... 2 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]

Normalized One-mode projection:
[[0.1 0.  0.1 ... 0.1 0.  0. ]
 [0.  0.3 0.  ... 0.  0.  0. ]
 [0.1 0.  0.2 ... 0.2 0.  0. ]
 ...
 [0.1 0.  0.2 ... 0.2 0.  0. ]
 [0.  0. 

In [17]:
print(investingproximity)

[[0.1 0.  0.  ... 0.1 0.  0. ]
 [0.  0.3 0.1 ... 0.  0.  0. ]
 [0.  0.1 0.1 ... 0.  0.  0. ]
 ...
 [0.1 0.  0.  ... 0.2 0.  0. ]
 [0.  0.  0.  ... 0.  0.1 0. ]
 [0.  0.  0.  ... 0.  0.  0.1]]


In [20]:
n = votingproximity.shape[0]
print(n)
politicians = range(n)

# Create DataFrame
df = pd.DataFrame([(i, j, votingproximity[i, j], investingproximity[i, j], female[i, j], state[i, j], party[i, j])
                   for i in politicians for j in politicians if i != j],
                  columns=['Politician1', 'Politician2', 'VotingProximity', 'InvestingProximity', 'Female', 'State', 'Party'])

# Export to CSV
df.to_csv('proximity_data.csv', index=False)

33


In [3]:
A = np.array([[0],[1],[0],[0],[1],[0],[0],[0],[1],[0],[0],[0],[1],[1],[0],[0],[0],[0],[1],[0],[1],[1],[0],[0],[1],[0],[1],[0],[0],[0],[1],[0]])

In [4]:
    B=A.T
    print('Transpose of A:')
    print(B)
    print()

    Q=A@B
    print('One-mode projection:')
    print(Q)
    print()
    
    female = Q
    print('Normalized One-mode projection:')
    print(female)

Transpose of A:
[[0 1 0 0 1 0 0 0 1 0 0 0 1 1 0 0 0 0 1 0 1 1 0 0 1 0 1 0 0 0 1 0]]

One-mode projection:
[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]]

Normalized One-mode projection:
[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]]


In [5]:
A = np.array([[1],[0],[1],[0],[0],[1],[0],[0],[1],[1],[0],[1],[1],[1],[1],[0],[0],[1],[0],[0],[1],[0],[1],[1],[0],[1],[0],[1],[1],[1],[1],[1]])

In [6]:
    B=A.T
    print('Transpose of A:')
    print(B)
    print()

    Q=A@B
    print('One-mode projection:')
    print(Q)
    print()
    
    party = Q
    print('Normalized One-mode projection:')
    print(party)

Transpose of A:
[[1 0 1 0 0 1 0 0 1 1 0 1 1 1 1 0 0 1 0 0 1 0 1 1 0 1 0 1 1 1 1 1]]

One-mode projection:
[[1 0 1 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 [1 0 1 ... 1 1 1]
 ...
 [1 0 1 ... 1 1 1]
 [1 0 1 ... 1 1 1]
 [1 0 1 ... 1 1 1]]

Normalized One-mode projection:
[[1 0 1 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 [1 0 1 ... 1 1 1]
 ...
 [1 0 1 ... 1 1 1]
 [1 0 1 ... 1 1 1]
 [1 0 1 ... 1 1 1]]


In [7]:
A = np.array([[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0],[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0],[0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0],[0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]])

In [8]:
    B=A.T
    print('Transpose of A:')
    print(B)
    print()

    Q=A@B
    print('One-mode projection:')
    print(Q)
    print()
    
    state = Q
    print('Normalized One-mode projection:')
    print(state)

Transpose of A:
[[1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 

In [20]:
n = votingproximity.shape[0]
print(n)
politicians = range(n)

# Create DataFrame
df = pd.DataFrame([(i, j, votingproximity[i, j], investingproximity[i, j], female[i, j], state[i, j], party[i, j])
                   for i in politicians for j in politicians if i != j],
                  columns=['Politician1', 'Politician2', 'VotingProximity', 'InvestingProximity', 'Female', 'State', 'Party'])

# Export to CSV
df.to_csv('proximity_data.csv', index=False)

32
